nodes:
  - name: telegraf
    listenaddr: 0.0.0.0:6666
    db: telegraf
    interval: 30
    idletimeout: 10
    querytracing: 0
    writetracing: 0
  - name: syscxp
    listenaddr: 0.0.0.0:6667
    db: syscxp
    interval: 30
    idletimeout: 10
    querytracing: 0
    writetracing: 0
measurements:
  - name: _default_
    backends: [telegraf1, telegraf2]
  - name: snmp
    backends: [telegraf1, telegraf2]
  - name: icmp
    backends: [syscxp1, syscxp2]
backends:
  - name: telegraf1
    url: http://192.168.211.73:8086
    db: telegraf
    interval: 300
    timeout: 10000
    timeoutquery: 600000
    maxrowlimit: 10000
    checkinterval: 1000
    rewriteinterval: 10000
  - name: telegraf2
    url: http://192.168.211.137:8086
    db: telegraf
    interval: 300
    timeout: 10000
    timeoutquery: 600000
    maxrowlimit: 10000
    checkinterval: 1000
    rewriteinterval: 10000
  - name: syscxp1
    url: http://192.168.211.73:8086
    db: syscxp
    interval: 300
    timeout: 10000
    timeoutquery: 600000
    maxrowlimit: 10000
    checkinterval: 1000
    rewriteinterval: 10000
  - name: syscxp2
    url: http://192.168.211.137:8086
    db: syscxp
    interval: 300
    timeout: 10000
    timeoutquery: 600000
    maxrowlimit: 10000
    checkinterval: 1000
    rewriteinterval: 10000
